### ISSUE TITLE
 🎯 What can I work on ? (Javascript SDK)

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-nodejs#182]
## Features
- [ ] Existing APIs: https://openfoodfacts.github.io/openfoodfacts-server/api/ref-v3/
- [ ] https://openfoodfacts.github.io/openfoodfacts-server/api/ref-v2/
- [ ] New api to document: see API changelog

## Roadmap
- [ ] List of new APIs to implement: https://github.com/openfoodfacts/api-documentation/issues

**Comment by arybhatt4533** [comment]
I've recently implemented URL inspection (get_url) in the Python SDK (#410) and noticed that the Explorer project aims to reuse this JS SDK. I'd like to implement similar URL exposure features here to help decoupling the frontend.

**Comment by VaiTon** [comment]
@arybhatt4533 this is a tracker bug, feel free to open another one for the feature you were thinking of
